### ISSUE TITLE
Wine and Proton stopped working [5.13]

### ISSUE THREAD

**Issue by jarrard** [xanmod/linux#177]
It seems 5.13 does not work with steam proton or wine.
Likely reason. Futex2 too new, incompatible with steam and wine in general. 

5.12 worked fine.  Default kernel 5.13 works.

I am using the manjaro version of xanmod if that is any help. Maybe the AUR has a bug.

**Comment by xanmod** [comment]
Already using the latest wine/proton version?

**Comment by xanmod** [comment]
I've identified the issue. A fix revision will be released soon.

**Comment by xanmod** [comment]
https://github.com/xanmod/linux/commit/135256c6766dfbac8857ccb9de9f1c5bf735fbf0

**Comment by jarrard** [comment]
Cheers, Hopefully it trickles down to manjaro aur.

Yes been using latest proton and wine.

**Comment by jarrard** [comment]
Just to let you know, that patch sort of worked but not 100%.

Some games are back to working, while others not so much. For example Risen3 works, but KCD and Mortal2Online do not.  

KCD complains about some TAG definitions on load up while Mortal2Online just fails loading. 

I'll drop back to 5.12 in the meanwhile until this is all sorted out as I believe the mainline 5.13 kernel has this issue also to some degree. Wish I could make a bug report about this but I have little knowledge of whats going wrong or if its just me, some people are suggesting its a me problem.... so back to 5.12 until otherwise.

**Comment by xanmod** [comment]
See if there isn't a new futex2 compatible Proton version. The legacy futex function MULTIPLE_WAIT for fsync has been discontinued in 5.13.

**Comment by xanmod** [comment]
See if there is a new futex2 compatible Proton version. The legacy futex function MULTIPLE_WAIT for fsync has been discontinued in 5.13.

**Comment by jarrard** [comment]
There is none that I know of...

**Comment by jarrard** [comment]
It seems this issue is related to using fsync/futex2 system on NTFS drives. Someone else has confirmed only their NTFS mounted games have issues.  I can confirm this appears to be the case.

**Comment by xanmod** [comment]
That wasn't it. Released new revision (5.13.6-xanmod2) with FUTEX_WAIT_MULTIPLE rebase for v5.13+.

**Comment by xanmod** [comment]
If users are having problems with nfts-3g driver via fuse, you can use the new ntfs3 kernel driver
`sudo modprobe ntfs3 && udisksctl mount -b /dev/### -t ntfs3`

**Comment by jarrard** [comment]
Cool thanks. 

I made a bugzilla report on the base kernel page but I think I was wrong. It affected NTFS but I'm not sure if it was futex/fsync related since those patches come after the fact. 

Once -6 appears I'll grab it.

**Comment by xanmod** [comment]
As ntfs-3g is the default driver in most distros, I believe you should report problems to the fuse project.

**Comment by jarrard** [comment]
The issue appears to still be happening with xanmod5.13-6 (haven't tried -7) but what I've discovered is that it only happens %50 of the time, if you keep rebooting then eventually it will work, but is random.

**Comment by RoyShapiro** [comment]
@xanmod Can confirm the same issue with the same symptoms, including that rebooting seems to randomly fix this, as stated here https://github.com/xanmod/linux/issues/177#issuecomment-894662058 in **5.14.0-xanmod1**.
As I was already aware of the bug and it's source (the kernel) from 5.13, but not the reasons behind it, I purposefully rebooted the system 5 times. On 1 of these 5 times the bug reappeared.
On kernel 5.13, in my mileage, it appeared on 2-3 out of 5 reboots.
Considering it happens with vanilla Wine too, and is (unreliably) fixed by reboots, I doubt it is tied to futex or (at least directly) to ntfs-3g, the latter specifically for the fact that reboots help randomly, although I might be wrong here.

No such issues appear on linux-xanmod-lts (namely 5.10 series or older).
