### ISSUE TITLE
no good responsiveness with cacule

### ISSUE THREAD

**Issue by mabod** [xanmod/linux#190]
Today I gave 5.13.11-xanmod1-cacule-1 a try on Arch Linux. I tested the responsiveness with my own test scenario and the result is not good.

My test scenario for responsiveness:
I am using memory load, not CPU load, as the background for a responsiveness test. I use `memtester 4.5.1-1` to create pressure on the memory. For that I open one terminal window per CPU core and run one memtester process in each of these terminal windows.On my PC with a Ryzen 7 3700X this is 16 windows with 16 memtester process in total.

I use the following script `memtester-loop.sh` to automate the startup of all memteser procesess:

memtester-loop.sh:
```
#!/usr/bin/zsh

mem=$1
iter=$2

if [[ $1 ]];
then
    mem=$1
else    
    mem=8192
fi
if [[ $2 ]];
then
    iter=$2
else
    iter=1
fi

for i in $(seq 1 $iter);
do
    echo "iter $i"
    xfce4-terminal -H --command "memtester $mem 1" &> /dev/null & 
done
```

Then I execute: 

`memtester-loop.sh 200m 16` 

to create the 16 terminal resp. memtester processes

When all memtester process are running I use another terminal window to start the mpv movie player to play a full HD video. 

`mpv --hwdec=auto my-full-HD-test-movie.mkv`

This is the resonsiveness test. I am checking how log it takes to start the movie, if the playback is smooth or choppy and if I can interact with the movie player and scroll back and forth.

There is only one CPU scheduler I have tested to far which is passing this test brilliantly, and that is MuQSS as it is found in the liquorix kernel. But cacule is not doing good at all.

With cacule the movie player is not even starting the movie. It takes infinitely long. I have to kill a few memtester windows before the movie starts. This is bad. And it is even worse than xanmod with regular CFS scheduler.

EDIT:

I tested also with  `kernel.sched_interactivity_factor=50`. With this value 50 the movie gets started. But the playback is choppy, the sound is delayed, etc. Pretty much the same "feeling" like with the stock Arch kernel.

**Comment by hamadmarri** [comment]
Hi @mabod

I am afraid that your test scenario itself is not a valid responsiveness test neither realistic. If you don't mind, could you please test with https://github.com/hamadmarri/os-scheduler-responsiveness-test

Either run:
`python3 responsiveness.py -i1 -p$(nproc) --np 4`
This test interactivity while cpus on load

or compile a kernel with `make -j$(nproc)`
and on separate terminal run `python3 responsiveness.py -i1 -t120`
This test interactivity with cpus+I/O loads.

The reason why I am saying your test is not realistic is that no real scenario nor an application will keep allocating big chunks of memory, locks it, and free it in short time. This tool is just to stress memory to discover faults.

Also based on the results you're experiencing, I interpret it in different way where xanmod cfs or xanmod cacule are giving more preferences to memory allocating and give the priority to allocate memory. It makes more sense to allocate memory fast and give it more priority since it helps to enhance responsiveness and let programs open faster. That's how I would see it.

Another thing, you didn't show how good/bad xanmod + cacule with the `memtester` itself. I am not sure if memtester can show you any results like how fast is the allocating/freeing the memory. 

Please try another test methods/tools, if you don't like the tool I gave above you can try https://github.com/ckolivas/interbench by Con.

You have judged that `no good responsiveness with cacule` based on a single test method which you came up with where I can see it is not a proper way to test responsiveness by.

So I am asking you please to show the results of other tests tools to measure interactivity and compare them. In case cacule failed all of them (the os-scheduler-responsiveness-test and interbench) then I can consider your claim is right and I will look to fix that. Also, I would consider your method of testing as proper if it is consistent with other tools results.

Thanks

**Comment by mabod** [comment]
I tested three kernels with `python3 responsiveness.py -i1 -p$(nproc) --np 4`

But I do not know how to interpret the results.

**5.13.11-xanmod1-cacule-1**
```
0 prime time:  33.845921200999996s
1 prime time:  33.798348634999996s
2 prime time:  33.25201113999999s
3 prime time:  33.271721093s
4 prime time:  33.580660557s
5 prime time:  33.517782295s
6 prime time:  33.514362155s
7 prime time:  33.395131316000004s
8 prime time:  33.176465639s
9 prime time:  33.640183238999995s
10 prime time:  33.588238102999995s
11 prime time:  33.604372565000006s
12 prime time:  33.431051432000004s
13 prime time:  33.19108031600001s
14 prime time:  33.84784753699999s
15 prime time:  33.524402591s
0 total response time:  0.14249521700003243s  runs:  17  average:  0.008382071588237202s
```
**5.13.10-arch1-1**
```
0 prime time:  33.544113773999996s
1 prime time:  33.29710540199999s
2 prime time:  33.36879977700001s
3 prime time:  33.441545153s
4 prime time:  33.427372616999996s
5 prime time:  33.378714724s
6 prime time:  33.419370064999995s
7 prime time:  33.465825476999996s
8 prime time:  33.496270985s
9 prime time:  33.27391831199999s
10 prime time:  33.50397478399999s
11 prime time:  33.36521136900001s
12 prime time:  33.43841286s
13 prime time:  33.35156721199999s
14 prime time:  33.44793541s
15 prime time:  33.455074188000005s
0 total response time:  0.22685772599997023s  runs:  17  average:  0.013344572117645307s
```
**5.13.10-zen1-1-zen**
```
0 prime time:  33.288489716000015s
1 prime time:  33.26336171099996s
2 prime time:  33.393781338s
3 prime time:  33.31663387499998s
4 prime time:  33.247394454000016s
5 prime time:  33.30924929899999s
6 prime time:  33.29795723000001s
7 prime time:  33.23208272100004s
8 prime time:  33.35268454300001s
9 prime time:  33.35427356299999s
10 prime time:  33.22885856400001s
11 prime time:  33.33019901999995s
12 prime time:  33.24620030599999s
13 prime time:  33.26569176300001s
14 prime time:  33.29834943700001s
15 prime time:  33.373382950999996s
0 total response time:  0.15559521800008724s  runs:  17  average:  0.009152659882358073s
```

**Comment by hamadmarri** [comment]
less total response time: and  average: the better

**Comment by mabod** [comment]
ok. Understood. I will keep xanmod-cacule as my default kernel for the time being. Lets see how that works out.
