### ISSUE TITLE
Clear Linux O3 patch - no vectorization

### ISSUE THREAD

**Issue by SicLuceatLux** [xanmod/linux#287]
The O3 as KBUILD flag is highly controversial as seen in many phoronix articles and the comment section. Lets not forget the rather aversial standpoint of Torvalds concerning o3.

Moreover it was not always beneficial to use the o3 flag as seen here https://www.phoronix.com/review/linux-kernel-o3

But as pointed out by some comment  in this article https://www.phoronix.com/news/Linux-6.0-Drops-O3-Kconfig

Intel is using this line for the kernel compilation as part of Clear Linux:

`KBUILD_CFLAGS += -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -mno-avx2 -O3 -fno-tree-vectorize -march=westmere -mpopcnt `

https://github.com/clearlinux-pkgs/linux/blob/71fbe0406686178c6a209a515c174df7ef77e4e4/0133-novector.patch

How about checking this one out and maybe using it?

**Comment by SicLuceatLux** [comment]
addendum in combination with the distinct march selction it might be worthwhile to remove -march=westmere and also add -mno-avx512f to disable avx also on the newer Intel CPU scompletely in case march=native ist going to be used

**Comment by xanmod** [comment]
11ee0e35471cb4f3e76a34203f9f72e2ba38a1ee

Thanks for the suggestion @SicLuceatLux

At the beginning of the project, these more aggressive optimizations were the default for xanmod kernel-wide builds instead of just arch/x86 space. The clearlinux approach seems safer to me.

I did initial testing with the new x86_64 psABI extensions (x86-64-v2/-v3/-v4) across the kernel, but still no good results in the benchmarks.

**Comment by SicLuceatLux** [comment]
Hi, thanks for the replay  will also do some more benchmarking .... time is my only issue :)
