### ISSUE TITLE
Xanmod 6.0.3 doesn't boot - Kubuntu 22.04

### ISSUE THREAD

**Issue by TerrorSquad** [xanmod/linux#313]
I updated recently to the latest version of the xanmod kernel - 6.0.3 and my PC refused to start correctly.

Upon powering my PC, I would see the Grub menu (I run multiboot Kubuntu/Windows), then after I chose Ubuntu (the first option), booting would resume as previously with the boot splash screen visible, but it would stop there and get stuck. It wouldn't progress to the login manager.

Older version - 6.0.2 runs completely fine.

Here are the specs:
```
OS: Kubuntu 22.04.1 LTS x86_64 
Host: MS-7C84 1.0 
Kernel: 6.0.2-x64v1-xanmod1 
Shell: zsh 5.8.1 
Resolution: 2560x1440 
DE: Plasma 5.25.5 
WM: KWin 
Theme: [Plasma], Breeze [GTK3] 
Icons: Papirus-Light [Plasma], Papirus-Light [GTK2/3] 
Terminal: yakuake 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: NVIDIA GeForce RTX 3070 Lite Hash Rate 
Nvidia Driver Version: 520.56.06 
Memory: 3576MiB / 64240MiB 
```

**Comment by iamonefm** [comment]
It is highly likely that nvidia kernel modules are missing.

**Comment by TerrorSquad** [comment]
Thanks @iamonefm. I'll report back in a few hours if that solved the issue.

**Comment by applike-ss** [comment]
i had to manually update to the 520 drivers via the ubuntu drivers tool and the manually installed the dkms module for 520 as well and then it worked for me.
Also running ubuntu 22.04 and using a GeForce GTX 750 Ti with 3 screens.

**Comment by TerrorSquad** [comment]
Reinstalling nvidia drivers did solve the issue.
We can close this ticket.
Thank you.

**Comment by applike-ss** [comment]
Does anyone else actually have flickering issues in chrome and sometimes (rarely) partial ghost images?

**Comment by TerrorSquad** [comment]
@applike-ss I had that issue, and didn't find a solution for it unfortunately.
Going back to the generic driver that came with the distro solved the problem.

**Comment by applike-ss** [comment]
In fact i returned to 5.19.14 and still got some (but not all) of the issues. Interestingly this only happens with chrome, but not with chromium or firefox. Especially due to the similarity of the browsers i would have expected chromium to show the same issue.
Whenever the nvidia driver can't be loaded i only have 1 screen for use (however i do have 3 at my desk), so going back to stock drivers wouldn't work well for me - unless it did actually not load the nouveau driver but simply vesa.
