### ISSUE TITLE
Concerning the use of ffast-math

### ISSUE THREAD

**Issue by ovlx** [xanmod/linux#387]
I've noticed that xanmod enables ffast-math globally for x86,  While concerns for 03 breaking stuff has largely been a non-issue for a long time, ffast-math is a different story, since it breaks the IEEE standard, most often this is fine since results do not have to be perfect,  for the kernel its hard to know if there are any parts that require IEEE compliance to work correctly .  

in particular fno-math-errno  which is enabled by ffast-math, could be an issue, also most of the other optimizations should have no effect since the kernel avoids doing floating point calculations in the first place. 

Given the small performance uplift, and the unknown risk of breakage, it seems like a bad Idea to enable it globally.
I suggest removing the ffast-math flag  from  the Add-more-x86_64-optimizations.  or at the very least enabling ftrapping-math and fmath-errno to reduce risk of breakage.

**Comment by xanmod** [comment]
In seven years we haven't had memory overflow issues or instability when using -ffast-math with -fstack-protector-strong in internal builds, but yes, you're right.

Most fp optimizations don't make sense to the kernel causing overhead beyond adding functions that violate IEEE semantics.

Since the day you posted this issue, I've reviewed the gcc and llvm documentation and made a new testing journey.

The -fexcess-precision=fast -freciprocal-math -fcx-limited-range flags have been kept. They will slightly reduce the precision in divisions for smaller cycles in x86 instruction operations.

**Comment by xanmod** [comment]
In seven years we haven't had memory overflow issues or instability when using -ffast-math with -fstack-protector-strong in internal builds, but yes, you're right. Most fp optimizations don't make sense to the kernel causing overhead beyond adding functions that violate IEEE semantics.

Right after posting this issue I reviewed the gcc and llvm documentation and went on a new testing journey.

The `-fexcess-precision=fast -freciprocal-math -fcx-limited-range` flags have been kept. They will slightly reduce the precision in divisions for less cycles in x86 instruction operations.
